Fix "Cannot read property 'catch' of undefined" errors on TS unit tests
There're apparently a few cases where we can't simply use the .catch()
method over the Promises returned by some APIs, because there could end
up being called over an undefined object i.e. some functions inside
browserActionAPI.ts, cosmeticFilterEvents.ts and browserAction.ts,
which would results in errors like this running npm run test-unit:

  Summary of all failing tests
  FAIL components/test/brave_extension/background/reducers/shieldsPanelReducer_test.ts (8.315 s)
    ● braveShieldsPanelReducer › WINDOW_FOCUS_CHANGED › calls shieldsPanelState.updateFocusedWindow

      TypeError: Cannot read property 'catch' of undefined

        50 | export const setBadgeText = (tabId: number, text: string) => {
        51 |   if (chrome.browserAction) {
      > 52 |     chrome.browserAction.setBadgeText({
           |     ^
        53 |       tabId,
        54 |       text: String(text)
        55 |     }).catch((e) => { console.error(e) })

This CL fixes this using a "try { await <async func> } catch(e) { .. }"
statement instead in those cases, which implies making the functions
where this is done asynchronous and adapting tests as needed.